name: Build X-UI Android ARM64 with CGO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install cross-compilation dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Replace binary filename in all files
      run: |
        find . -type f -exec sed -i 's/xray-linux-arm64/com.gray.boxstream/g' {} +

    - name: Replace hardcoded core path in Go source
      run: |
        sed -i 's|"bin/xray-linux-arm64"|"bin/com.gray.boxstream"|g' internal/constant/constant.go

    - name: Build x-ui for Android ARM64 with CGO
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 1
        CC: aarch64-linux-gnu-gcc
      run: |
        go build -o x-ui-android-arm64 main.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: x-ui-android-arm64
        path: x-ui-android-arm64
